### ISSUE TITLE
error: incompatible integer to pointer conversion with newer clang

### ISSUE THREAD

**Issue by chenrui333** [mywave82/opencubicplayer#121] opened 2024-12-24 06:00 UTC
👋 seeing some build errors with newer clang

```
  clang -g -O2 -fno-common -fPIC -D_DARWIN_C_SOURCE -Wall -I.././ file.c -o file.o -c
  file.c:1209:10: error: call to undeclared function 'memrchr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   1209 |                 name = memrchr (path, '/', strlen(path) - 1);
        |                        ^
  file.c:1209:10: note: did you mean 'memchr'?
  /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk/usr/include/_string.h:70:7: note: 'memchr' declared here
     70 | void    *memchr(const void *__s, int __c, size_t __n);
        |          ^
  file.c:1209:8: error: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
   1209 |                 name = memrchr (path, '/', strlen(path) - 1);
        |                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 errors generated.
  make[1]: *** [file.o] Error 1
  make: *** [stuff] Error 2
```

full error log, https://github.com/Homebrew/homebrew-core/actions/runs/12475938384/job/34820106435#step:3:764

relates to https://github.com/Homebrew/homebrew-core/pull/202302

**Comment by mywave82** [comment] 2024-12-24 08:00
Conforming To
The memchr() function conforms to SVr4, 4.3BSD, C89, C99, POSIX.1-2001.


Hmm,  have to add a check in configure.ac and add alternative implementation in stuff/compat.h

**Comment by mywave82** [comment] 2024-12-25 12:07
Could you please try to apply this patch

c724e4aaf91815af11bfc4c5c2354d1dcb0c7be6

If it works I will apply it to master and it will be part of the next release (can take some time before that happen, but you can add the patch to your the build manifest until that happens)

**Comment by mywave82** [comment] 2024-12-30 01:02
The patch mentioned above has been applied to master. Please reopen if the problem is still present in v3.0.1

**Closed by mywave82** 2024-12-30 01:02 UTC
