### ISSUE TITLE
OCP fails to launch with libjpeg-turbo library (macOS Ventura)

### ISSUE THREAD

**Issue by chiefjazzdiewltr** [mywave82/opencubicplayer#102] opened 2023-07-04 10:23 UTC
<img width="990" alt="Screenshot 2023-07-04 at 10 12 11 PM" src="https://github.com/mywave82/opencubicplayer/assets/16767027/d3ccad37-a8c8-427a-80ab-bf7abe513e3a">

libjpeg-turbo (along with every other dependency) is install with the prefix '/opt/local' as I use MacPorts for my package manager. The configure flags I used are below

```
PATH=$PATH LDFLAGS=-L/opt/local/lib CFLAGS=-I/opt/local/include CXXFLAGS=-I/opt/local/include CPPFLAGS=-I/opt/local/include CPPCXXFLAGS=-I/opt/local/include LD_LIBRARY_PATH=-L/opt/local/lib ./configure \
--prefix=/opt/local \
--exec-prefix=/opt/local 
--libdir=/opt/local/lib 
--includedir=/opt/local/include \
--with-coreaudio \
--with-ncurses \
--without-desktop_file_install \
--without-update-desktop-database --without-update-mime-database \
--without-x11 \
--with-unifontdir-ttf=/Library/Fonts
```

**Comment by mywave82** [comment] 2023-07-04 18:06
(I am not a regular MacOS user myself, so this is from searching online)

When you have dylib files outside the normal search paths, it seems that you have two choices:
a) update DYLD_LIBRARY_PATH in your shell (this is just temporary)

export DYLD_LIBRARY_PATH=/opt/local/lib:$DYLD_LIBRARY_PATH
TERM=xterm-color ocp-curses

b) use otool and install_name_tool to inspect and modify the .dylib files that needs modifications
 https://www.fullstaq.com/knowledge-hub/blogs/an-alternative-to-macos-dyld-library-path

**Comment by chiefjazzdiewltr** [comment] 2023-07-05 08:59
<img width="1074" alt="Screenshot 2023-07-05 at 8 56 18 PM" src="https://github.com/mywave82/opencubicplayer/assets/16767027/ee7b9599-cf31-4e00-879d-abdb6b98d712">
I changed all the dylib paths in the libocp.dylib to their full paths and while it fixed the libjpeg issue I have this one now:
<img width="1074" alt="Screenshot 2023-07-05 at 8 57 26 PM" src="https://github.com/mywave82/opencubicplayer/assets/16767027/d143b162-048f-4b55-b8a7-940d8fd995fb">

**Comment by mywave82** [comment] 2023-07-05 10:16
Please provide config.log, config.h and Rules.make, so I can see what was detected regarding iconv/libiconv. I know that ocp in general works when compiled by HomeBrew

**Comment by chiefjazzdiewltr** [comment] 2023-07-05 11:18
[config.log](https://github.com/mywave82/opencubicplayer/files/11957201/config.log)
[Rules.make.log](https://github.com/mywave82/opencubicplayer/files/11957215/Rules.make.log)
[config.h.log](https://github.com/mywave82/opencubicplayer/files/11957216/config.h.log)
These are the 3 files, I did have to append .log to the Rules.make and config.h files as github comments don't support those types apparently.

**Comment by mywave82** [comment] 2023-07-05 11:38
SDL2 expects to find libiconv.2.dylib  (notice the .2. , do you have that file? I would probably expect it to be a symlink to libiconv.dylib)

**Comment by chiefjazzdiewltr** [comment] 2023-07-05 12:18
<img width="1552" alt="Screenshot 2023-07-06 at 12 15 24 AM" src="https://github.com/mywave82/opencubicplayer/assets/16767027/860c4f57-2151-45a7-b048-a79629390b9e">
I do have that file and I changed it back to that use that specific one but no dice. Also I looked at the libSDL2 dylib and saw it was looking for a /usr/lib/libiconv dylib so I changed that to use the one in my /opt/local folder and that didn't help either.

**Comment by mywave82** [comment] 2023-07-05 12:38
Why your copy of libSDL2-2.0.0.0.dylib does not accept your libiconv.2.dylib I do not fully know. There might be some versioning on the symbols it expects. Where did your copies of libSDL2-2.0.0.dylib and libiconv.dylib come from?

Beware that there are multiple implementations of iconv with different companioned header files that might not be binary compatible with each-others.

**Comment by chiefjazzdiewltr** [comment] 2023-07-05 12:44
Both of them are from MacPorts so I'm not sure either, there is a libsdl-framework port on MacPorts but I don't know if that would matter

**Comment by mywave82** [comment] 2023-07-05 12:46
Can I suggest that you inquire MacPorts about the problem getting libSDL2 + iconv to work in a third party project?

**Comment by mywave82** [comment] 2023-07-05 12:49
(or compile with SDL support, so that only Open Cubic Player needs iconv, which should match the header files provided by MacPorts). Open Cubic Player can display visual using text/curses only and has native audio support on MacOS.

make uninstall
make clean
./configure --help                   # check for configure options that disables SDL1.x and SDL2.x support

**Comment by chiefjazzdiewltr** [comment] 2023-07-05 13:43
Yea it actually runs if I compile it without SDL1.x and SDL2.x, so I'll send an enquiry to MacPorts about it in the morning.

**Comment by mywave82** [comment] 2023-07-10 09:32
I am closing this issue as I do not believe the problem is OpenCubicPlayer, but the configuration of the build-system.

If you however find details that are wrong: please re-open and provide new new information or create a PullRequest

**Closed by mywave82** 2023-07-10 09:32 UTC
